### ISSUE TITLE
Don't use CompletionServiceImpl.createCompletionParameters

### ISSUE THREAD

**Issue by donnerpeter** [beeender/ComradeNeovim#1]
It'll be removed in 2019.2

**Comment by beeender** [comment]
@donnerpeter Thanks a lot for the reminding!

I was quite happy when `CompletionServiceImpl.createCompletionParameters` added in `2018.2`. But since it will be removed in `2019.2`, it seems no way to create a `CompletionParameters` in the plugin anymore. The `CompletionProcessEx` is package protected so I cannot inherit and create an instance for `CompletionInitializationUtil.prepareCompletionParameters()`.

Is there any better way for plugin to hook into the `CompletionService`?

**Comment by donnerpeter** [comment]
You can invoke the code completion action and take results from the `Lookup` after it's finished.
